// Rate limiting constants
export const RATE_LIMIT_CONFIG = {
  DISCOVERY_CALL_MAX_REQUESTS: 3,
  DISCOVERY_CALL_WINDOW_MS: 300000, // 5 minutes
  APPLICATION_MAX_REQUESTS: 2,
  APPLICATION_WINDOW_MS: 300000, // 5 minutes
  DEFAULT_MAX_REQUESTS: 3,
  DEFAULT_WINDOW_MS: 60000, // 1 minute
} as const;

// Validation length limits
export const VALIDATION_LIMITS = {
  NAME_MAX_LENGTH: 50,
  EMAIL_MAX_LENGTH: 254,
  PHONE_MIN_LENGTH: 10,
  PHONE_MAX_LENGTH: 15,
  LOCATION_MAX_LENGTH: 100,
  PROFESSION_MAX_LENGTH: 100,
  COMPANY_MAX_LENGTH: 100,
  EDUCATION_MAX_LENGTH: 200,
  INTERESTS_MAX_LENGTH: 500,
  LIFESTYLE_MAX_LENGTH: 500,
  VALUES_MAX_LENGTH: 500,
  PREVIOUS_RELATIONSHIPS_MAX_LENGTH: 1000,
  RELATIONSHIP_GOALS_MAX_LENGTH: 1000,
  IDEAL_PARTNER_LOCATION_MAX_LENGTH: 100,
  IDEAL_PARTNER_PROFESSION_MAX_LENGTH: 100,
  IDEAL_PARTNER_QUALITIES_MAX_LENGTH: 1000,
  EXPECTATIONS_MAX_LENGTH: 1000,
  BACKGROUND_INFO_MAX_LENGTH: 1000,
  QUESTIONS_MAX_LENGTH: 1000,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
} as const;

