// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://temsybfglhylzpxmntka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbXN5YmZnbGh5bHpweG1udGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDQ1NDUsImV4cCI6MjA2OTU4MDU0NX0.bxUE7rkSxS4HG9GQpKL3gnmyWMAh9lyl4gLc5GoS4U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});